repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
    name: check-merge-conflict
  - id: detect-private-key
    name: detect-private-key
  - id: end-of-file-fixer
    name: end-of-file-fixer
  - id: no-commit-to-branch
    name: no-commit-to-branch
  - id: trailing-whitespace
    name: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  -   id: flake8
      args: [--per-file-ignores=__init__.py:F401]
- repo: https://github.com/PyCQA/isort
  rev: 5.11.2
  hooks:
  - id: isort
