version: "3.9"
services:
  browser:
    image: przemekk1385/browser:latest
  redis:
    image: redis
  app:
    build:
      context: .
    environment:
      - API_KEY
      - APP_PORT
      - BROWSER_URL
      - ENVIRONMENT
      - MAIL_FROM
      - MAIL_PASSWORD
      - MAIL_PORT
      - MAIL_SERVER
      - MAIL_SUBJECT
      - MAIL_USERNAME
      - ORIGINS
      - REDIS_URL
      - ROLLBAR_ACCESS_TOKEN
    command: >-
      gunicorn -k izba_reader.workers.UvicornWorker -b 0.0.0.0:8000 izba_reader.main:app
    depends_on:
      - browser
      - redis
    ports:
      - "${APP_PORT}:8000"
