version: "3.9"

services:
  browser:
    image: przemekk1385/browser:latest
  app:
    build:
      context: .
    environment:
      API_KEY: ${APP_API_KEY}
      BROWSER_URL: ${APP_BROWSER_URL}
      ENVIRONMENT: ${APP_ENVIRONMENT}
      MAIL_FROM: ${APP_MAIL_FROM}
      MAIL_PASSWORD: ${APP_MAIL_PASSWORD}
      MAIL_PORT: ${APP_MAIL_PORT}
      MAIL_SERVER: ${APP_MAIL_SERVER}
      MAIL_SUBJECT: ${APP_MAIL_SUBJECT}
      MAIL_USERNAME: ${APP_MAIL_USERNAME}
      ORIGINS: ${APP_ORIGINS}
      REDIS_URL: ${APP_REDIS_URL}
      SENTRY_DSN: ${APP_SENTRY_DSN}
    command: >-
      uvicorn izba_reader.main:app
      --host 0.0.0.0
      --port 8000
      --root-path ${APP_ROOT_PATH}
      --workers 4
    depends_on:
      - browser
      - redis
    ports: ["${APP_SERVICE_PORT:-8000}:8000"]

networks:
  shared_services:
    external: true

