version: "3.9"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
    environment:
      - ENVIRONMENT
      - MAIL_FROM
      - MAIL_PASSWORD
      - MAIL_PORT
      - MAIL_SERVER
      - MAIL_SUBJECT
      - MAIL_USERNAME
      - REDIS_URL
      - ROLLBAR_ACCESS_TOKEN
    command: uvicorn izba_reader:main.app
    depends_on:
      - redis
    ports:
      - "1304:8000"
