docker/build:
	doppler run -- docker-compose build

docker/build/dev:
	doppler run -c dev -- docker-compose -f docker-compose.dev.yml build

docker/stop:
	docker ps -qf name=^$(basename $(pwd)).+$ | xargs -L1 docker stop

docker/up:
	doppler run -- docker-compose up -d

docker/up/dev:
	doppler run -c dev -- docker-compose -f docker-compose.dev.yml up -d
