uvicorn/run:
	doppler secrets get APP_ROOT_PATH --plain \
| xargs -I {} doppler run -c dev -- \
uvicorn izba_reader.main:app \
--host 127.0.0.1 \
--port 8000 \
--root-path {} \
--workers 4

uvicorn/reload:
	doppler run -c dev -- \
uvicorn izba_reader.main:app \
--reload
