version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - run:
          name: "Install Chrome-required libraries"
          command: |
            sudo apt-get update &&
            sudo apt-get install -y \
              libxcursor1 \
              libxdamage1 \
              libcups2 \
              libasound2 \
              libpangocairo-1.0-0 \
              libatk1.0-0 \
              libatk-bridge2.0-0 \
              libgtk-3-0
      - run:
          name: "Install poetry"
          command: poetry install
      - run:
          name: "Run pytest"
          command: poetry run pytest -s
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"

workflows:
  digitalocean-deploy:
    jobs:
      - build
      - deploy:
          context: izba-reader-prod
          requires:
            - build
