version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.1
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - run:
          name: "Install Chrome-required libraries"
          command: |
            sudo apt-get update &&
            sudo apt-get install -y \
              libxcursor1 \
              libxdamage1 \
              libcups2 \
              libasound2 \
              libpangocairo-1.0-0 \
              libatk1.0-0 \
              libatk-bridge2.0-0 \
              libgtk-3-0
      - run:
          name: "Install poetry"
          command: poetry install
      - run:
          name: "Run pytest"
          command: poetry run pytest -s

workflows:
  heroku-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          context: izba-reader-dev
          requires:
            - build
          filters:
            branches:
              only: master
