version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.4
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Clone browser repository"
          command: >-
            mkdir -p browser
            && cd browser
            && git clone https://github.com/przemekk1385/browser.git .
      - run:
          name: "Build and run browser"
          command: cd browser && make docker-build && make docker-run
      - run:
          name: "Install dependencies"
          command: poetry install
      - run:
          name: "Run pytest"
          command: poetry run pytest -s
      - persist_to_workspace:
          root: ~/project
          paths:
            - browser
            - izba_reader
            - .dockerignore
            - docker-compose.yml
            - Dockerfile
            - entrypoint.sh
            - poetry.lock
            - pyproject.toml
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    parameters:
      build_file:
        type: string
        default: $CIRCLE_PROJECT_REPONAME-$CIRCLE_SHA1.tar.gz
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: >-
            tar czvf << parameters.build_file >>
            -C ~/project .
            --exclude="__pycache__"
            --exclude=".git"
          name: Compress build
      - run:
          command: >-
            scp
            -oStrictHostKeyChecking=no
            -v
            << parameters.build_file >>
            $USER@$IP:~/.
          name: Copy build
      - run:
          command: >-
            ssh
            -oStrictHostKeyChecking=no
            -v
            $USER@$IP
            "./deploy-docker.sh
            $CIRCLE_PROJECT_REPONAME
            << parameters.build_file >>
            $DOPPLER_TOKEN"
          name: Run remote deployment script

workflows:
  digitalocean-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
