version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.4
      - image: cimg/redis:6.2.6
      - image: przemekk1385/browser:latest
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: poetry install
      - run:
          name: "Run black"
          command: poetry run black . --check
      - run:
          name: "Run isort"
          command: poetry run isort . --check
      - run:
          name: "Run flake8"
          command: poetry run flake8 .
      - run:
          name: "Run pytest"
          command: poetry run pytest -s
  deploy:
    docker:
      - image: arvindr226/alpine-ssh:latest
    parameters:
      app_dirname:
        type: string
        default: $CIRCLE_PROJECT_REPONAME
      token:
        type: string
        default: $DOPPLER_TOKEN_PRD
    steps:
      - run:
          command: >-
            ssh
            -oStrictHostKeyChecking=no
            -v
            $USER@$IP
            "./deploy-docker.sh
            << parameters.app_dirname >>
            << parameters.token >>"
          name: Run remote deployment script

workflows:
  digitalocean-deploy:
    jobs:
      - build-and-test
      - deploy:
          name: deploy-prd
          requires:
            - build-and-test
          filters:
            branches:
              only: /^release\/v[0-9]+(\.[0-9]+)*$/
      - deploy:
          name: deploy-stg
          requires:
            - build-and-test
          filters:
            branches:
              only: master
          app_dirname: $CIRCLE_PROJECT_REPONAME-stg
          token: $DOPPLER_TOKEN_STG
