name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.10.4-bullseye

    services:
      browser:
        image: przemekk1385/browser:latest
        ports:
          - 3000
      redis:
        image: redis
        ports:
          - 6379

    steps:
    - uses: actions/checkout@v3
    - name: Install libGL
      run: >-
        apt-get update && apt-get install -y libgl1
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: >-
        poetry update && poetry install
    - name: Check code formatting with black
      run: >-
        poetry run black . --check
    - name: Check order of imports with isort
      run: >-
        poetry run isort . --check
    - name: Lint with flake8
      run: >-
        poetry run flake8 .
    - name: Test with pytest
      run: >-
        poetry run pytest
