name: build

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.10-bullseye

    services:
      browser:
        image: przemekk1385/browser:latest
      redis:
        image: redis

    steps:
      - name: Set up GNU C Library
        run: apt-get install -y glibc
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Poetry
        run: pip install poetry
      - name: Build
        run: poetry install --no-root
      - name: Lint
        run: |
          poetry run black . --check
          poetry run isort . --check
          poetry run flake8 .
      - name: Test
        run: poetry run pytest
        env:
          BROWSER_URL: http://browser:3000
          REDIS_URL: redis://redis:6379
